### ISSUE TITLE
Bay of Plenty imagery ordering

### ISSUE THREAD

**Issue by silvispace** [linz/basemaps-config#187]
Hi LINZ team,
I noticed the BoP ordering issue seems to have crept back in. The imagery shown on the basemap is from the [2017 capture](https://basemaps.linz.govt.nz/#@-37.7560879,176.1084356,z18.263). But the most recent imagery is from the [2019 capture](https://basemaps.linz.govt.nz/?i=01ED81W4KDQQRW9PEQ9KS7T8DV#@-37.7560879,176.1084356,z18.263). 
Thanks for the great work on this system.

**Comment by blacha** [comment]
Thanks for reporting this!

I can confirm that `tauranga_urban_2017_0-1m` is being rendered on top of `bay-of-plenty_urban_2018-19_0-1m`

I have made a PR to adjust the priority of the bop 2019 imagery.

#188

**Comment by blacha** [comment]
Going to basemaps link you now, I see the Bay of plenty 2019

![image](https://user-images.githubusercontent.com/1082761/132144606-e8017fa0-a3a7-474d-9c55-997c14e951d8.png)
