### ISSUE TITLE
Invercargill aerial imagery prioritises 0.1m over 0.05m

### ISSUE THREAD

**Issue by SheaSmith** [linz/basemaps-config#198]
It appears the ordering for the Invercargill aerial imagry is prioritising the 0.1m imagery over the higher quality (and as far as I can tell, from the same time period) 0.05m imagery. For example: [Default basemaps](https://basemaps.linz.govt.nz/#@-46.4130206,168.3476286,z20.1353) vs [basemap with the 0.05m layer selected](https://basemaps.linz.govt.nz/?i=01ED82DPKVVWA818DY9QQ9GS0J#@-46.4130206,168.3476286,z20.1353).

**Comment by blacha** [comment]
Thanks for reporting this!

They are currently layered that way in the configuration https://github.com/linz/basemaps-config/blob/master/config/tileset/aerial.json#L71

I will double check with the imagery people to see if they should be swapped.

**Comment by blacha** [comment]
Looks like they are in the wrong order, I have made a pull request to change the order.

It should hopefully be deployed shortly.

**Comment by blacha** [comment]
@SheaSmith this has now been deployed, your browser may cache the tiles so you may need to hard refresh your page.

When looking at those two links I now see the same imagery.

Thanks again for reporting the issue.
