### ISSUE TITLE
Aerial Photo ordering. 

### ISSUE THREAD

**Issue by dchaps** [linz/basemaps-config#64]
It looks like Bay of Plenty 0.125m Urban Aerial Photos (2015-2016) is prioritised over Bay of Plenty 0.1m Urban Aerial Photos 2018-2019).
Is there any particular reason for this?
Cheers
Dan

**Comment by blacha** [comment]
Sorry for my super slow response here..

Looking at basemaps you are correct the BoP 2015 is indeed showing up ontop of the BoP 2019 imagery. This looks to be a bug where the 2015 is prioritized higher than the 2015.

The attribution even shows we are using the wrong layer:
https://basemaps.linz.govt.nz/#@-37.78374847,176.32391917,z20.1086
![image](https://user-images.githubusercontent.com/1082761/122848085-f7a26880-d35c-11eb-92cf-1fc053aec4cd.png)


vs the 2019 imagery https://basemaps.linz.govt.nz/?i=01ED81W4KDQQRW9PEQ9KS7T8DV#@-37.78374847,176.32391917,z20.1086

![image](https://user-images.githubusercontent.com/1082761/122848052-e9544c80-d35c-11eb-83a3-a9b78b2d48d9.png)
